# Generated by Django 4.1.3 on 2022-11-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='food-categories-images/')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Food categories',
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Menu categories',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MenuItemFeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('title_en', models.CharField(max_length=63, null=True)),
                ('title_ar', models.CharField(max_length=63, null=True)),
            ],
            options={
                'verbose_name_plural': 'Menu-item feature categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('title_en', models.CharField(max_length=63, null=True)),
                ('title_ar', models.CharField(max_length=63, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Restaurant statuses',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('slogan', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True)),
                ('rating', models.FloatField(default=0.0, editable=False)),
                ('num_of_reviewers', models.IntegerField(default=0, editable=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants-images/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='restaurants-images/')),
                ('address', models.CharField(max_length=255)),
                ('_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='restaurants.foodcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurantstatus')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('title_en', models.CharField(max_length=63, null=True)),
                ('title_ar', models.CharField(max_length=63, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menuitemfeaturecategory')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.ImageField(blank=True, null=True, upload_to='food-items-images/')),
                ('rating', models.FloatField(default=0.0, editable=False)),
                ('num_of_reviewers', models.IntegerField(default=0, editable=False)),
                ('available_now', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('avg_prep_duration_sec', models.SmallIntegerField(default=0, editable=False)),
                ('prep_time_nums', models.IntegerField(default=0, editable=False)),
                ('features', models.ManyToManyField(blank=True, null=True, to='restaurants.menuitemfeature')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.menucategory')),
            ],
            options={
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant'),
        ),
    ]
