# Generated by Django 4.1.3 on 2022-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='features',
            field=models.ManyToManyField(to='restaurants.menuitemfeature'),
        ),
    ]
