# Generated by Django 4.1.3 on 2023-09-30 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_city_active_city_created_at_city_updated_at_and_more'),
        ('restaurants', '0003_alter_restaurant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='_lat',
            new_name='_latitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='_long',
            new_name='_longitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='available_now',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories-images/'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemfeature',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemfeature',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemfeature',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemfeaturecategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemfeaturecategory',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemfeaturecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='num_of_reviewers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurants.restaurantstatus'),
        ),
        migrations.AlterField(
            model_name='restaurantstatus',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantstatus',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantstatus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant'], name='restaurant_index'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner'], name='owner_index'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='city_index'),
        ),
    ]
