# Generated by Django 4.1.3 on 2023-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename__lat_restaurant__latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
