# Generated by Django 4.1.3 on 2023-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rename_is_available_menuitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='num_of_reviewers',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='num_of_reviews',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
