# Generated by Django 4.1.3 on 2023-10-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_remove_menuitem_num_of_reviewers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menucategory',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='blocked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
