# Generated by Django 4.1.3 on 2023-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_rename_creation_time_foodcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
