# Generated by Django 4.1.3 on 2023-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_menucategory_title_ar_menucategory_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ar',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
