# Generated by Django 4.1.3 on 2023-09-29 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=31)),
                ('currency_en', models.CharField(max_length=31, null=True)),
                ('currency_ar', models.CharField(max_length=31, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.country')),
            ],
            options={
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='country_index'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state'], name='state_index'),
        ),
    ]
