# Generated by Django 4.1.3 on 2023-09-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.country')),
            ],
            options={
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ar', models.CharField(max_length=128, null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('ordering', 'name'),
            },
        ),
    ]
