# Generated by Django 4.1.3 on 2023-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_city_active_city_created_at_city_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='state_index',
        ),
        migrations.RemoveIndex(
            model_name='state',
            name='country_index',
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='no_repeated_cities_for_a_state'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='no_repeated_states_for_a_country'),
        ),
    ]
