# Generated by Django 4.1.3 on 2022-12-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_date_time_order_created_at_orderstatus_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_duration_sec',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prep_duration_sec',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus'),
        ),
    ]
